# Generated by Django 6.0.2 on 2026-03-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=list, help_text='List of feature strings'),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
